export const categories = [
  { value: "laptop", name: "Laptop" },
  { value: "laptop_accessory", name: "Laptop accessory" },
  { value: "phone", name: "Phone" },
  { value: "phone_accessory", name: "Phone accessory" },
];

export const laptopBrands = [
  "Acer",
  "Alienware",
  "Apple",
  "Asus",
  "Avita",
  "Chuwi",
  "Clevo",
  "Dell",
  "Eluktronics",
  "Eurocom",
  "Fujitsu",
  "Gateway",
  "Gigabyte",
  "Google",
  "HP",
  "Honor",
  "Huawei",
  "iBall",
  "Infinix",
  "Lenovo",
  "LG",
  "Microsoft",
  "MSI",
  "Origin PC",
  "Panasonic",
  "Razer",
  "Realme",
  "Samsung",
  "Sony",
  "System76",
  "Toshiba",
  "VAIO",
  "Xiaomi",
  "Zoostorm",
  "Framework",
];

export const laptopAccessories = [
  "Laptop Bag",
  "Wireless Mouse",
  "Wired Mouse",
  "Keyboard",
  "Laptop Stand",
  "Cooling Pad",
  "Webcam",
  "USB Hub",
  "External Hard Drive",
  "External SSD",
  "Flash Drive",
  "Headphones",
  "Earphones",
  "Speakers",
  "Docking Station",
  "Charger",
  "Power Bank for Laptop",
  "Screen Protector",
  "Keyboard Protector",
  "Cleaning Kit",
  "HDMI Cable",
  "Ethernet Cable",
  "Bluetooth Adapter",
  "Wi-Fi Adapter",
  "Stylus Pen",
  "Laptop Lock",
  "Privacy Screen Filter",
  "Monitor",
  "External GPU (eGPU)",
  "Memory Card Reader",
  "USB-C Adapter",
  "Laptop Skins or Decals",
];
export const phoneBrands = [
  "Apple",
  "Samsung",
  "Huawei",
  "Xiaomi",
  "Oppo",
  "Vivo",
  "OnePlus",
  "Realme",
  "Motorola",
  "Nokia",
  "Google",
  "Sony",
  "Asus",
  "Tecno",
  "Infinix",
  "Itel",
  "Lenovo",
  "Honor",
  "ZTE",
  "LG",
  "HTC",
  "Meizu",
  "Micromax",
  "Lava",
  "Panasonic",
  "Sharp",
  "Coolpad",
  "BlackBerry",
  "Alcatel",
  "iTel",
  "BLU",
  "Gionee",
];
export const phoneAccessories = [
  "Phone Case",
  "Screen Protector",
  "Charging Cable",
  "Wall Charger",
  "Wireless Charger",
  "Power Bank",
  "Earphones",
  "Headphones",
  "Bluetooth Headset",
  "Bluetooth Speaker",
  "Car Charger",
  "Phone Holder",
  "Pop Socket",
  "Ring Holder",
  "Phone Tripod",
  "Selfie Stick",
  "Camera Lens Attachment",
  "MicroSD Card",
  "SIM Card Adapter",
  "USB OTG Cable",
  "Smartwatch",
  "Fitness Tracker",
  "Phone Cleaning Kit",
  "Phone Cooling Fan",
  "Gaming Controller",
  "Stylus Pen",
  "Phone Wallet",
  "Phone Lanyard",
  "VR Headset",
  "AR Glasses",
];

export const colors = [
  "Black",
  "White",
  "Gray",
  "Silver",
  "Gold",
  "Blue",
  "Red",
  "Green",
  "Yellow",
  "Purple",
  "Pink",
  "Orange",
  "Brown",
  "Beige",
  "Cyan",
  "Magenta",
];
